spring.application.name=NeoPractice

spring.datasource.url=jdbc:postgresql://localhost:5432/neopracDB
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret=-tYl1(zdJ<Ys^6awctLkGz#=r)BUB!ld2DmOE]%N}9T
jwt.expiration=86400000

spring.liquibase.enabled=false